// apps/svelte-app/src/App.svelte
<script lang="ts">
  import {
    NxAudioLoader,
    NxBallTriangleLoader,
    NxBarsLoader,
  } from '@ngeenx/nx-svelte-svg-loaders';

  const sizes = [10, 15, 20, 25, 30, 25, 40, 50],
    loaderTypes = [
      'Audio',
      'Ball Triangle',
      'Bars',
      'Circles',
      'Grid',
      'Heart',
      'Oval',
      'Puff',
      'Rings',
      'Spinning Circles',
      'Tail Spin',
      'Three Dots',
    ];
</script>

<main>
  <header>Svelte SVG Loaders</header>

  {#each loaderTypes as loaderType}
    <section class="flex flex-row items-center justify-center gap-5 p-4">
      <h1>{loaderType} Loaders</h1>

      <div>
        {#each sizes as size}
          {#if loaderType === 'Audio'}
            <NxAudioLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Ball Triangle'}
            <NxBallTriangleLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Bars'}
            <NxBarsLoader isLoading={true} {size} />
          {/if}
        {/each}
      </div>
    </section>
  {/each}
</main>

<style lang="scss">
  @import './app.scss';
</style>

// apps/angular-app/src/app/app.component.ts
import { Component } from "@angular/core";
import { RouterModule } from "@angular/router";
import { NxWelcomeComponent } from "./nx-welcome.component";
import {
  NxAudioLoaderComponent,
  NxBallTriangleLoaderComponent,
  NxBarsLoaderComponent,
  NxCirclesLoaderComponent,
  NxOvalLoaderComponent,
} from "@ngeenx/nx-angular-svg-loaders";

@Component({
  standalone: true,
  imports: [
    NxWelcomeComponent,
    RouterModule,

    // SVG loader components
    NxOvalLoaderComponent,
    NxAudioLoaderComponent,
    NxBallTriangleLoaderComponent,
    NxBarsLoaderComponent,
    NxCirclesLoaderComponent,
  ],
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrl: "./app.component.scss",
})
export class AppComponent {
  public sizes: number[] = [10, 15, 20, 25, 30, 25, 40, 50];
}

<main>
  <!-- Oval Loader -->
  <section class="flex flex-row gap-5 justify-center p-4 items-center">
    <h1>Oval Loaders</h1>

    <div>
      @for (size of sizes; track $index) {
      <nx-angular-svg-oval-loader [isLoading]="true" [size]="size" />
      }
    </div>
  </section>

  <!-- Audio Loader -->
  <section class="flex flex-row gap-5 justify-center p-4 items-center">
    <h1>Audio Loaders</h1>

    <div>
      @for (size of sizes; track $index) {
      <nx-angular-svg-audio-loader [isLoading]="true" [size]="size" />
      }
    </div>
  </section>

  <!-- Ball Triangle Loader -->
  <section class="flex flex-row gap-5 justify-center p-4 items-center">
    <h1>Ball Triangle Loaders</h1>

    <div>
      @for (size of sizes; track $index) {
      <nx-angular-svg-ball-triangle-loader [isLoading]="true" [size]="size" />
      }
    </div>
  </section>

  <!-- Bars Loader -->
  <section class="flex flex-row gap-5 justify-center p-4 items-center">
    <h1>Bars Loaders</h1>

    <div>
      @for (size of sizes; track $index) {
      <nx-angular-svg-bars-loader [isLoading]="true" [size]="size" />
      }
    </div>
  </section>

  <!-- Circles Loader -->
  <section class="flex flex-row gap-5 justify-center p-4 items-center">
    <h1>Circles Loaders</h1>

    <div>
      @for (size of sizes; track $index) {
      <nx-angular-svg-circles-loader [isLoading]="true" [size]="size" />
      }
    </div>
  </section>

  <!-- Grid Loader -->
  <section class="flex flex-row gap-5 justify-center p-4 items-center">
    <h1>Grid Loaders</h1>

    <div>
      @for (size of sizes; track $index) {
      <nx-angular-svg-grid-loader [isLoading]="true" [size]="size" />
      }
    </div>
  </section>

  <!-- Heart Loader -->
  <section class="flex flex-row gap-5 justify-center p-4 items-center">
    <h1>Heart Loaders</h1>

    <div>
      @for (size of sizes; track $index) {
      <nx-angular-svg-hearts-loader [isLoading]="true" [size]="size" />
      }
    </div>
  </section>

  <!-- Puff Loader -->
  <section class="flex flex-row gap-5 justify-center p-4 items-center">
    <h1>Puff Loaders</h1>

    <div>
      @for (size of sizes; track $index) {
      <nx-angular-svg-puff-loader [isLoading]="true" [size]="size" />
      }
    </div>
  </section>

  <!-- Rings Loader -->
  <section class="flex flex-row gap-5 justify-center p-4 items-center">
    <h1>Rings Loaders</h1>

    <div>
      @for (size of sizes; track $index) {
      <nx-angular-svg-rings-loader [isLoading]="true" [size]="size" />
      }
    </div>
  </section>

  <!-- Spinning Circles Loader -->
  <section class="flex flex-row gap-5 justify-center p-4 items-center">
    <h1>Spinning Circles Loaders</h1>

    <div>
      @for (size of sizes; track $index) {
      <nx-angular-svg-spinning-circles-loader
        [isLoading]="true"
        [size]="size"
      />
      }
    </div>
  </section>

  <!-- Tail Spin Loader -->
  <section class="flex flex-row gap-5 justify-center p-4 items-center">
    <h1>Tail Spin Loaders</h1>

    <div>
      @for (size of sizes; track $index) {
      <nx-angular-svg-tail-spin-loader [isLoading]="true" [size]="size" />
      }
    </div>
  </section>
</main>
