// apps/react-app/src/app/app.tsx
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import React from 'react';

import { sizes, loaderTypes } from '@ngeenx/nx-svg-shared-utils';

import {
  NxAudioLoader,
  NxBallTriangleLoader,
  NxBarsLoader,
  NxCirclesLoader,
  NxGridLoader,
  NxHeartsLoader,
  NxOvalLoader,
  NxPuffLoader,
  NxRingsLoader,
  NxSpinningCirclesLoader,
  NxTailSpinLoader,
  NxThreeDotsLoader,
} from '@ngeenx/nx-react-svg-loaders';

import '/libs/utils/nx-svg-shared-utils/src/styles/app.component.scss';

export function App() {
  return (
    <main>
      <header>React SVG Loaders</header>

      {loaderTypes.map((loaderType, loaderIndex) => (
        <section
          key={loaderIndex}
          className="flex flex-row items-center justify-center gap-5 p-4"
        >
          <h1>{loaderType} Loaders</h1>

          <div>
            {sizes.map((size, sizeIndex) => (
              <React.Fragment key={sizeIndex}>
                {loaderType === 'Audio' && (
                  <NxAudioLoader isLoading={true} size={size} />
                )}
                {loaderType === 'Ball Triangle' && (
                  <NxBallTriangleLoader isLoading={true} size={size} />
                )}
                {loaderType === 'Bars' && (
                  <NxBarsLoader isLoading={true} size={size} />
                )}
                {loaderType === 'Circles' && (
                  <NxCirclesLoader isLoading={true} size={size} />
                )}
                {loaderType === 'Grid' && (
                  <NxGridLoader isLoading={true} size={size} />
                )}
                {loaderType === 'Hearts' && (
                  <NxHeartsLoader isLoading={true} size={size} />
                )}
                {loaderType === 'Oval' && (
                  <NxOvalLoader isLoading={true} size={size} />
                )}
                {loaderType === 'Puff' && (
                  <NxPuffLoader isLoading={true} size={size} />
                )}
                {loaderType === 'Rings' && (
                  <NxRingsLoader isLoading={true} size={size} />
                )}
                {loaderType === 'Spinning Circles' && (
                  <NxSpinningCirclesLoader isLoading={true} size={size} />
                )}
                {loaderType === 'Tail Spin' && (
                  <NxTailSpinLoader isLoading={true} size={size} />
                )}
                {loaderType === 'Three Dots' && (
                  <NxThreeDotsLoader isLoading={true} size={size} />
                )}
              </React.Fragment>
            ))}
          </div>
        </section>
      ))}
    </main>
  );
}

export default App;

// apps/svelte-app/src/App.svelte
<script lang="ts">
  import { sizes, loaderTypes } from '@ngeenx/nx-svg-shared-utils';

  import {
    NxAudioLoader,
    NxBallTriangleLoader,
    NxBarsLoader,
    NxCirclesLoader,
    NxGridLoader,
    NxHeartsLoader,
    NxOvalLoader,
    NxPuffLoader,
    NxRingsLoader,
    NxSpinningCirclesLoader,
    NxTailSpinLoader,
    NxThreeDotsLoader,
  } from '@ngeenx/nx-svelte-svg-loaders';
</script>

<main>
  <header>Svelte SVG Loaders</header>

  {#each loaderTypes as loaderType}
    <section class="flex flex-row items-center justify-center gap-5 p-4">
      <h1>{loaderType} Loaders</h1>

      <div>
        {#each sizes as size}
          {#if loaderType === 'Audio'}
            <NxAudioLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Ball Triangle'}
            <NxBallTriangleLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Bars'}
            <NxBarsLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Circles'}
            <NxCirclesLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Grid'}
            <NxGridLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Hearts'}
            <NxHeartsLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Oval'}
            <NxOvalLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Puff'}
            <NxPuffLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Rings'}
            <NxRingsLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Spinning Circles'}
            <NxSpinningCirclesLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Tail Spin'}
            <NxTailSpinLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Three Dots'}
            <NxThreeDotsLoader isLoading={true} {size} />
          {/if}
        {/each}
      </div>
    </section>
  {/each}
</main>

<style lang="scss">
  @import './../../../libs/utils/nx-svg-shared-utils/src/styles/app.component.scss';
</style>
