// apps/svelte-app/src/App.svelte
<script lang="ts">
  import {
    NxAudioLoader,
    NxBallTriangleLoader,
    NxBarsLoader,
    NxCirclesLoader,
    NxGridLoader,
    NxHeartsLoader,
    NxOvalLoader,
    NxPuffLoader,
    NxRingsLoader,
    NxSpinningCirclesLoader,
    NxTailSpinLoader,
    NxThreeDotsLoader,
  } from '@ngeenx/nx-svelte-svg-loaders';

  import { sizes, loaderTypes } from '@ngeenx/nx-svg-shared-utils';
</script>

<main>
  <header>Svelte SVG Loaders</header>

  {#each loaderTypes as loaderType}
    <section class="flex flex-row items-center justify-center gap-5 p-4">
      <h1>{loaderType} Loaders</h1>

      <div>
        {#each sizes as size}
          {#if loaderType === 'Audio'}
            <NxAudioLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Ball Triangle'}
            <NxBallTriangleLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Bars'}
            <NxBarsLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Circles'}
            <NxCirclesLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Grid'}
            <NxGridLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Heart'}
            <NxHeartsLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Oval'}
            <NxOvalLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Puff'}
            <NxPuffLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Rings'}
            <NxRingsLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Spinning Circles'}
            <NxSpinningCirclesLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Tail Spin'}
            <NxTailSpinLoader isLoading={true} {size} />
          {/if}

          {#if loaderType === 'Three Dots'}
            <NxThreeDotsLoader isLoading={true} {size} />
          {/if}
        {/each}
      </div>
    </section>
  {/each}
</main>

<style lang="scss">
  @import './app.scss';
</style>

// apps/vue-app/src/app/App.vue
<template>
  <main>
    <header>Vue SVG Loaders</header>

    <section
      v-for="(loaderType, loaderIndex) in loaderTypes"
      :key="loaderIndex"
      class="flex flex-row items-center justify-center gap-5 p-4"
    >
      <h1>{{ loaderType }} Loaders</h1>

      <div>
        <template v-if="loaderType === 'Audio'">
          <NxAudioLoader
            v-for="(size, sizeIndex) in sizes"
            :key="sizeIndex"
            :isLoading="true"
            :size="size"
          />
        </template>
        <template v-if="loaderType === 'Ball Triangle'">
          <NxBallTriangleLoader
            v-for="(size, sizeIndex) in sizes"
            :key="sizeIndex"
            :isLoading="true"
            :size="size"
          />
        </template>
        <template v-if="loaderType === 'Bars'">
          <NxBarsLoader
            v-for="(size, sizeIndex) in sizes"
            :key="sizeIndex"
            :isLoading="true"
            :size="size"
          />
        </template>
        <template v-if="loaderType === 'Circles'">
          <NxCirclesLoader
            v-for="(size, sizeIndex) in sizes"
            :key="sizeIndex"
            :isLoading="true"
            :size="size"
          />
        </template>
        <template v-if="loaderType === 'Grid'">
          <NxGridLoader
            v-for="(size, sizeIndex) in sizes"
            :key="sizeIndex"
            :isLoading="true"
            :size="size"
          />
        </template>
        <template v-if="loaderType === 'Heart'">
          <NxHeartsLoader
            v-for="(size, sizeIndex) in sizes"
            :key="sizeIndex"
            :isLoading="true"
            :size="size"
          />
        </template>
        <template v-if="loaderType === 'Oval'">
          <NxOvalLoader
            v-for="(size, sizeIndex) in sizes"
            :key="sizeIndex"
            :isLoading="true"
            :size="size"
          />
        </template>
        <template v-if="loaderType === 'Puff'">
          <NxPuffLoader
            v-for="(size, sizeIndex) in sizes"
            :key="sizeIndex"
            :isLoading="true"
            :size="size"
          />
        </template>
        <template v-if="loaderType === 'Rings'">
          <NxRingsLoader
            v-for="(size, sizeIndex) in sizes"
            :key="sizeIndex"
            :isLoading="true"
            :size="size"
          />
        </template>
        <template v-if="loaderType === 'Spinning Circles'">
          <NxSpinningCirclesLoader
            v-for="(size, sizeIndex) in sizes"
            :key="sizeIndex"
            :isLoading="true"
            :size="size"
          />
        </template>
        <template v-if="loaderType === 'Tail Spin'">
          <NxTailSpinLoader
            v-for="(size, sizeIndex) in sizes"
            :key="sizeIndex"
            :isLoading="true"
            :size="size"
          />
        </template>
        <template v-if="loaderType === 'Three Dots'">
          <NxThreeDotsLoader
            v-for="(size, sizeIndex) in sizes"
            :key="sizeIndex"
            :isLoading="true"
            :size="size"
          />
        </template>
      </div>
    </section>
  </main>
</template>

<script>
import { sizes, loaderTypes } from '@ngeenx/nx-svg-shared-utils';

import {
  NxAudioLoader,
  NxBallTriangleLoader,
  NxBarsLoader,
  NxCirclesLoader,
  NxGridLoader,
  NxHeartsLoader,
  NxOvalLoader,
  NxPuffLoader,
  NxRingsLoader,
  NxSpinningCirclesLoader,
  NxTailSpinLoader,
  NxThreeDotsLoader,
} from '@ngeenx/nx-vue-svg-loaders';

export default {
  components: {
    NxAudioLoader,
    NxBallTriangleLoader,
    NxBarsLoader,
    NxCirclesLoader,
    NxGridLoader,
    NxHeartsLoader,
    NxOvalLoader,
    NxPuffLoader,
    NxRingsLoader,
    NxSpinningCirclesLoader,
    NxTailSpinLoader,
    NxThreeDotsLoader,
  },
  data() {
    return {
      sizes: sizes,
      loaderTypes: loaderTypes,
    };
  },
};
</script>

<style scoped>
@import './app.scss';
</style>
